import Head from "next/head";
import styles from "@/styles/Home.module.css";
import NavBar from "../component/NavBar";
import Intro from "@/component/Intro";
import Story from "@/component/Story";
import Methods from "@/component/Methods";
import Session from "@/component/Session";

export default function Home() {
    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <NavBar />
                <Intro />
                <Story />
                <Methods />
                <Session />
            </main>
        </>
    );
}
